# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EZCoachSoccer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EZCoachSoccer
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'IQKeyboardManagerSwift'
  pod 'ImagePicker'
  pod 'DKImagePickerController'
  use_frameworks!

  target 'EZCoachSoccerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EZCoachSoccerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
